image:
  name: hugomods/hugo:exts
  entrypoint: [""]

pages:
  before_script:
    - apk add --no-cache git
    - git submodule update --init --recursive
  script:
    - hugo --minify
  artifacts:
    paths:
      - public
  only:
    - main